version: '3.8'

services:
  db:
    image: postgres:latest # Usando a imagem oficial do PostgreSQL
    container_name: java-crud-postgres # Nome do container
    environment:
      POSTGRES_USER: change-me
      POSTGRES_PASSWORD: change-me
      POSTGRES_DB: change-me
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
